### ISSUE TITLE
Getting error in window.createLemonSqueezy();

### ISSUE THREAD

**Issue by sulaimanwebdev** [lmsqueezy/nextjs-billing#1]
I downloaded the Lemon Squeezy Next JS billing repo. Everything work perfectly, but I get this error when I run the app it says **TypeError: window.createLemonSqueezy is not a function**

The error is in /components/plan.jsx

How can I fix this error?

<img width="959" alt="Screenshot 2024-02-04 at 7 00 30 PM" src="https://github.com/lmsqueezy/nextjs-billing/assets/74793541/245f0bb7-0e44-4561-97d7-c558b007089e">

**Comment by code-vagabond** [comment]
I encountered the same error, my fix is using the Script component included by nextjs instead which has a callback prop for when the script is loaded: 

`
      <Script
        src="https://app.lemonsqueezy.com/js/lemon.js"
        strategy="afterInteractive"
        onLoad={() => {
          window.createLemonSqueezy();
        }}
      />
`

**Comment by yahorbarkouski** [comment]
Add something like this to your client component:
```
 <Script src="https://assets.lemonsqueezy.com/lemon.js" defer onReady={handleScriptReady} />
```

and then handle it:
```
  const handleScriptReady = (): void => {
          console.log("LemonSqueezy loading");
          window.createLemonSqueezy();
          console.log("LemonSqueezy loaded");
      };
```
