### ISSUE TITLE
Reading from "node:crypto" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by sbmmahato** [lmsqueezy/nextjs-billing#10]
node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

Showing this error when building.

**Comment by brankoconjic** [comment]
Hey @sbmmahato,

You can directly import from `crypto` instead.

**Comment by sbmmahato** [comment]
Thanks. I already solved the issue. Also I was using 'use client'. Changing it to 'use server' fixed the problem
