### ISSUE TITLE
Buyer and Seller both mails going to seller account

### ISSUE THREAD

**Issue by mlbrothers** [lmsqueezy/nextjs-billing#7]
As title says, both mails are going to seller. Even when I resend receipt from my store, it comes to my own mail address.

**Comment by brankoconjic** [comment]
Hello,

That is expected and should happen  only in the  ["Test mode"](https://docs.lemonsqueezy.com/help/getting-started/test-mode).

**Comment by mlbrothers** [comment]
Got it, thanks!
